---
name: Security Scan

##########################################
# Start the job on push for all branches #
##########################################
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

###############
# Set the Job #
###############
jobs:
  tfsec:
    name: Run TFsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Security Scan
        uses: tfsec/tfsec-sarif-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Terraform security scan
#        uses: triat/terraform-security-scan@v1.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
